# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoManager < Formula
  desc "Repo manager allows you to check repo dependencies."
  homepage "https://github.com/kazhuravlev/repo-manager"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/repo-manager/releases/download/v0.2.1/repo-manager_0.2.1_Darwin_arm64.tar.gz"
      sha256 "049f8849eadb9bc88c8d114e059869cb566f5124fd429393fef195d7e87d46be"

      def install
        bin.install "repo-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazhuravlev/repo-manager/releases/download/v0.2.1/repo-manager_0.2.1_Linux_arm64.tar.gz"
      sha256 "93bcce9a7199c98497866a69ad09be9e47149bc98e55de9413af33c57def3c32"

      def install
        bin.install "repo-manager"
      end
    end
  end

  test do
    system "#{bin}/repo-manager help"
  end
end
