# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoManager < Formula
  desc "Repo manager allows you to check repo dependencies."
  homepage "https://github.com/kazhuravlev/repo-manager"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/repo-manager/releases/download/v0.1.1/repo-manager_0.1.1_Darwin_arm64.tar.gz"
      sha256 "11b220aff925023868a5b354cf60da7c818a553fd13a618636cbe6174d33a4d5"

      def install
        bin.install "repo-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazhuravlev/repo-manager/releases/download/v0.1.1/repo-manager_0.1.1_Linux_arm64.tar.gz"
      sha256 "3686886a9c77c3bd84b705e6c1f1d4b1c52cbba4b6d4bf4b2f920be25d0c3ac3"

      def install
        bin.install "repo-manager"
      end
    end
  end

  test do
    system "#{bin}/repo-manager help"
  end
end
